### ISSUE TITLE
Video from mobile Firefox is not sharing to participants

### ISSUE THREAD

**Issue by artem-gorokhovskii** [twilio/twilio-video-app-react#429]
I can't see a video from another user, who is using mobile Firefox.
But on device with mobile Firefox I can see a small screen with video (looks like I'm sharing video with participants).

**To Reproduce**
1. Connect to the meeting from PC (Chrome browser, for example)
2. Connect to the meeting from mobile (Firefox mobile browser)
3. Turn on video on mobile Firefox

**Expected behavior**
All participants can see the video from mobile Firefox

**Real behavior**
The only user of mobile Firefox can see his video.

**Screenshots**
PC user screen [Problem]: I can't see video from mobile Firefox:
![image](https://user-images.githubusercontent.com/45370857/108508993-b24a2d80-72cd-11eb-998a-62b22eca848d.png)

Mobile user screen [OK]: I see, that I'm sharing video from my camera:
![image](https://user-images.githubusercontent.com/45370857/108509105-dc9beb00-72cd-11eb-97a4-56315b740609.png)

**Environment (please complete the following information):**
 - OS: Android 9 (Samsung S8+)
 - Browser: Mobile Firefox 85.1.3
 - App Version: 0.2.1
 - Twilio-video: 2.9.0
 - Node.js version: 14.15.1

**Comment by timmydoza** [comment]
Thanks for the issue @artem-gorokhovskii!

Unfortunately, I wasn't able to reproduce this problem myself. Firefox on my Android device seemed to send video just fine.

I'm wondering - how often does this issue happen for you. Does firefox never send video? Or is it able to send video some of the time? I'm just curious about how frequently you encounter this issue .

**Comment by Galzk** [comment]
@timmydoza I've managed to reproduce this issue on Firefox nightly, please note this is the app:
https://play.google.com/store/apps/details?id=org.mozilla.fenix&hl=en&gl=US
They changed the app heavily, notice the bottom url bar, you might be running an older version

I'm running 87.0a1
Nightly 210221 17:02

I'm also running on a heavily modified fork so I would suggest this is an issue with Firefox and not this repo
Audio track received and working, video track is showing only on the mobile side, and isn't being received on other devices

**Comment by artem-gorokhovskii** [comment]
@timmydoza 
I have Firefox Daylight:
![image](https://user-images.githubusercontent.com/45370857/108880108-037e5800-7613-11eb-861c-0e460a7812a1.png)

@Galzk 
`They changed the app heavily, notice the bottom url bar, you might be running an older version`
I was asked where it would be more comfortable for me to situate url bar, at the top or at the bottom.

**Comment by timmydoza** [comment]
Thanks for the tip @Galzk! 

I tried running this app in Firefox Nightly, and I still could not reproduce the issue. Everything appeared to work just fine. 

> I'm also running on a heavily modified fork of twilio-video-app-react

I'm wondering if there was an issue that was introduced in these modifications. If you run a fresh build of this app from the `master` branch, are you still able to reproduce the issue? @artem-gorokhovskii have you modified the app? And if so, can you also reproduce the issue with a clean build of the app from the `master` branch?

Let me know if either of you have any ideas that could help me reproduce the bug. Thanks!

**Comment by artem-gorokhovskii** [comment]
@timmydoza Thanks for response.
I got Firefox from Play market, seems it is clear:
https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by timmydoza** [comment]
@artem-gorokhovskii I was asking if you are running a modified version of this Twilio video app (https://github.com/twilio/twilio-video-app-react), not Firefox. 

Since I can't reproduce the issue myself, I'm wondering if the issue lies on your end, if you happened to modify the code. If you have modified the code, can you try running a clean version of this Twilio video app (from the `master` branch) to see if you can still reproduce the issue? This will help us narrow down where the issue might be. 

I still can't reproduce the issue, so any additional information that you can provide about the problem will be very helpful. 

Thanks! And have a good weekend!

**Comment by Galzk** [comment]
Hey @timmydoza,
I've cloned the repo and tested on an Android phone again (Galaxy s9+)
The issue is still occuring
Take a look at the following video where I reproduce the issue:

https://user-images.githubusercontent.com/34302982/111666019-fae8fe00-881b-11eb-9a1a-2bccf4f351b3.mp4

**Comment by Ivan-Vetster** [comment]
I am reproducing this bug with no problems. It seems the mozzilla firefox on android is working only on H264 codec, VP8 is not sharing

**Comment by SlashKing** [comment]
I have also been able to reproduce this, albeit I have a home-rolled app. I make use of the hooks in this repo for the state management and experience identical behavior. After further investigation, can also confirm that the track is in fact published, it is simply not displaying for the recipient of the publication.

**Comment by Galzk** [comment]
@SlashKing Are you able to verify that x264 is working as expected?
@Ivan-Vetster Have you tested on a room with 2 participants or more? (To know if the stream goes trough a server, or peer to peer)

**Comment by timmydoza** [comment]
Hey @Galzk @Ivan-Vetster @SlashKing and @artem-gorokhovskii!

The twilio-video SDK recently released a new version which may fix the issue you are all encountering. [Version 2.13.1](https://github.com/twilio/twilio-video.js/releases/tag/2.13.1) of the SDK fixes a bug where Android Firefox Participants sometimes fail to publish VP8 VideoTracks in a Group Room. I've released a new version of this app which uses version 2.13.1 of the twilio-video SDK. 

I hope this solves the issue. Please let me know how this new SDK version works out for you. Thanks!!

**Comment by Galzk** [comment]
I have checked earlier today and the issue persists on my modified version

I'll try to reproduce on this repository as well in a few days

**Comment by Galzk** [comment]
@timmydoza Just verified, FIrefox still doesn't work on this repo with 2.13.1

**Comment by timmydoza** [comment]
Thanks @Galzk - I'll let our SDK engineers know.

**Comment by timmydoza** [comment]
Hey @Galzk  - I was wondering if you happen to have any room SIDs for any rooms where you experienced this issue with version 2.13.1? If you have any that you could provide, it could help us find the cause of the issue. 

Thanks!

**Comment by Galzk** [comment]
@timmydoza 
Hey,
I've made some progress!
First of all:
`RM82b0d4f860b5f24c08316cab78fb5f21`
This room's status was:
3 participants total
1. Desktop chrome (Didn't share video track, on purpose)
2. Firefox mobile (Shared video track)
3. Firefox desktop (Didn't share video track, on purpose)

I was able to see FF mobile's (2) video on chrome (1), but not on FF desktop (3)
Try to reproduce using FF desktop and FF mobile

**Comment by timmydoza** [comment]
Thanks for the additional information @Galzk!

I tried to reproduce the issue using the steps you provided, but I was not able to do so. I was able to see the video from the mobile FireFox participant in Desktop Firefox. 

Just curious, what device are you running mobile Firefox on? I'm wondering if this issue is only reproducible on certain devices. 

I'll take note of the information you provided and add it to the internal ticket that we have to track this issue.

**Comment by MuhammadTaimour95** [comment]
Hi @timmydoza! I am also having this issue. Using firefox android for one participant and desktop for the other. Cannot see firefox video on the desktop.

**Comment by MuhammadTaimour95** [comment]
@timmydoza Just tried with the latest version of this repository with general deployment to Twilio as mentioned in the repo readme. Still reproducing the issue i.e the video from the person who is using firefox mobile is not coming on desktop chrome or firefox. When I mute the video it shows avatar but when I unmute it  shows black screen.

**Comment by timmydoza** [comment]
I tried again, and I'm still not able to reproduce the issue described. If there is something wrong, I will need some more detailed steps to follow on how to reproduce the issue.

There hasn't been much traffic here, and this issue has been lingering for a while. Since we haven't been able to reproduce this problem on our side, I'm going to go ahead and close the issue for now. 

If this problem persists in a way that is consistently reproducible, then please open a new issue with detailed information on the problem and how to reproduce it and I will be more than happy to take a look. Thanks!
